### ISSUE TITLE
Tiny flags appearing as empty squares

### ISSUE THREAD

**Issue by xi-pinmping** [pridont/countryfetch-deno#7]
Hey, love the program but I am having a strange issue. 
It will not display the tiny flag but the ascii one is displayed no issues. Example attached below.
![Screenshot_20220627_161244](https://user-images.githubusercontent.com/84921777/176027706-259b9693-d2c6-421e-9882-def7cf029639.png)

Thanks for the neat terminal candy!

**Comment by pridont** [comment]
On some terminals the country code is displayed instead of the flag. The flag itself is an emoji, so I assume a specific font should be installed on the system and it only displays on terminals that can support it.

Here's the output on Alacritty:
![Screenshot_2022-06-28_11-30-51](https://user-images.githubusercontent.com/82287873/176119782-fa52590a-f358-40d2-a309-7cfd124348ae.png)

And here's the output on Kitty:
![Screenshot_2022-06-28_11-33-33](https://user-images.githubusercontent.com/82287873/176120377-0304712b-5699-4f0c-bcdb-ea1a9b010dbf.png)

It would be nice to find if there's a particular font dependency or it just needs the right terminal (or both).

**Comment by xi-pinmping** [comment]
Yea after making this issue I tried it on kitty and everything works perfectly with the same setup. Not quite sure where the dependency would lie since I use nerd font icons primarily.

**Comment by pridont** [comment]
What terminal do you use in the screenshot which shows squares?

**Comment by xi-pinmping** [comment]
Foot. I have recently made a full switch to kitty though, because despite how much I love foot, a lot of issues are shining through and I use my terminal for all that I can so I try to keep it looking nice. Foot for some reason struggles with image and video previews in ranger where kitty does not and I am working toward using 100% cli tools for day to day stuff so it makes a difference.

**Comment by pridont** [comment]
I see, it's a terminal specific issue then. Well, kitty is a great terminal emulator so it will serve you well.

Closing the issue.
